controller_manager:
  ros__parameters:
    update_rate: 500

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    flywheel_effort_controller:
      type: forward_command_controller/ForwardCommandController

flywheel_effort_controller:
  ros__parameters:
    joints: [flywheel_left_joint, flywheel_right_joint]
    interface_name: effort
