#!/usr/bin/env python3
"""Write a C2 coverage-only report; this command never builds an artifact."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "ros2_ws" / "src" / "tennis_robot"))

from tennis_robot.perception_covariance_calibration import CalibrationError  # noqa: E402
from tennis_robot.perception_covariance_evidence import assert_c2_coverage  # noqa: E402


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--evidence-dir", required=True, type=Path)
    parser.add_argument("--trial-manifest", required=True, type=Path)
    parser.add_argument("--report", required=True, type=Path)
    args = parser.parse_args()
    manifest = json.loads(args.trial_manifest.read_text(encoding="utf-8"))
    rows, summaries = [], {}
    for evidence in sorted(args.evidence_dir.glob("*.jsonl")):
        if evidence.name.endswith((".rejections.jsonl", ".non_target.jsonl")):
            continue
        rows.extend(json.loads(line) for line in evidence.read_text(encoding="utf-8").splitlines())
    for path in args.evidence_dir.glob("*.summary.json"):
        summary = json.loads(path.read_text(encoding="utf-8"))
        summaries[summary.get("trial_id", "")] = summary
    try:
        assert_c2_coverage(rows, manifest=manifest, summaries=summaries)
    except CalibrationError as exc:
        status, detail = "FAIL", str(exc)
    else:
        status, detail = "PASS", "All C2 coverage requirements passed."
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(
        "# C2 controlled Gazebo coverage report\n\n"
        f"- Gate: **{status}**\n"
        f"- Accepted evidence rows: {len(rows)}\n"
        f"- Detail: {detail}\n"
        "- Artifact: not generated by this command.\n",
        encoding="utf-8",
    )
    if status != "PASS":
        raise SystemExit(detail)


if __name__ == "__main__":
    main()
